from dataclasses import dataclass, field
from typing import List


@dataclass
class SkillGap:
    """
    Represents a missing skill between the resume
    and the target job description.
    """

    skill: str
    priority: str


@dataclass
class CourseRecommendation:
    """
    Represents a recommended learning course.
    """

    title: str
    provider: str
    url: str


@dataclass
class CareerRoadmap:
    """
    Represents a learning roadmap.
    """

    title: str
    steps: List[str] = field(default_factory=list)


@dataclass
class CareerReport:
    """
    Final report generated by Career Intelligence Engine.
    """

    ats_score: float

    match_score: float

    extracted_skills: List[str] = field(default_factory=list)

    missing_skills: List[SkillGap] = field(default_factory=list)

    recommended_courses: List[CourseRecommendation] = field(default_factory=list)

    roadmap: List[str] = field(default_factory=list)

    suggestions: List[str] = field(default_factory=list)